package Renderer::Plugin::Assets;
use Mojo::Base 'Mojolicious::Plugin', -signatures;

use Mojo::File qw(path);
use Mojo::JSON qw(decode_json);

my $staticRendererAssets;
my $staticPGAssets;
my $thirdPartyRendererDependencies;
my $thirdPartyPGDependencies;

sub register ($plugin, $app, $conf) {
	$app->helper(
		getAssetURL => sub ($c, $file, $language = $app->config->{language}) {
			my $renderRoot = $app->home;

			# Load the static files list generated by `npm install` the first time this method is called.
			unless ($staticRendererAssets) {
				my $staticAssetsList = $renderRoot->child('public', 'static-assets.json');
				$staticRendererAssets = readJSON($staticAssetsList);
				unless ($staticRendererAssets) {
					warn "ERROR: '$staticAssetsList' not found or not readable!\n"
						. "You may need to run 'npm install' from '$renderRoot/public'.";
					$staticRendererAssets = {};
				}
			}

			unless ($staticPGAssets) {
				my $staticAssetsList = path($ENV{PG_ROOT})->child('htdocs', 'static-assets.json');
				$staticPGAssets = readJSON($staticAssetsList);
				unless ($staticPGAssets) {
					warn "ERROR: '$staticAssetsList' not found or not readable!\n"
						. "You may need to run 'npm install' from '$ENV{PG_ROOT}/htdocs'.";
					$staticPGAssets = {};
				}
			}

			unless ($thirdPartyRendererDependencies) {
				my $packageJSON = $renderRoot->child('public', 'package.json');
				my $data        = readJSON($packageJSON);
				warn "ERROR: '$packageJSON' not found or not readable!\n"
					unless $data && defined $data->{dependencies};
				$thirdPartyRendererDependencies = $data->{dependencies} // {};
			}

			unless ($thirdPartyPGDependencies) {
				my $packageJSON = path($ENV{PG_ROOT})->child('htdocs', 'package.json');
				my $data        = readJSON($packageJSON);
				warn "ERROR: '$packageJSON' not found or not readable!\n"
					unless $data && defined $data->{dependencies};
				$thirdPartyPGDependencies = $data->{dependencies} // {};
			}

			# Check to see if this is a third party asset file in node_modules (either in renderer/public or pg/htdocs).
			# If so, then either serve it from a CDN if requested, or serve it directly with the library version
			# appended as a URL parameter.
			if ($file =~ /^node_modules/) {
				my $rendererFile = getThirdPartyAssetURL($c, $file, $thirdPartyRendererDependencies, 'publicFile');
				return $rendererFile if $rendererFile;

				my $pgFile = getThirdPartyAssetURL($c, $file, $thirdPartyPGDependencies, 'pgFile',);
				return $pgFile if $pgFile;
			}

			# If a right-to-left language is enabled (Hebrew or Arabic) and this is a css file that is not a third party
			# asset, then determine the rtl varaint file name.  This will be looked for first in the asset lists.
			my $rtlfile =
				($language =~ /^(he|ar)/ && $file !~ /node_modules/ && $file =~ /\.css$/)
				? $file =~ s/\.css$/.rtl.css/r
				: undef;

			# First check to see if this is a file in the renderer public location with a rtl variant.
			return $c->url_for('publicFile', static => $staticRendererAssets->{$rtlfile})->to_string
				if defined $rtlfile && defined $staticRendererAssets->{$rtlfile};

			# Next check to see if this is a file in the renderer public location.
			return $c->url_for('publicFile', static => $staticRendererAssets->{$file})->to_string
				if defined $staticRendererAssets->{$file};

			# Now check to see if this is a file in the pg htdocs location with a rtl variant.
			return $c->url_for('pgFile', static => $staticPGAssets->{$rtlfile})->to_string
				if defined $rtlfile && defined $staticPGAssets->{$rtlfile};

			# Next check to see if this is a file in the pg htdocs location.
			return $c->url_for('pgFile', static => $staticPGAssets->{$file})->to_string
				if defined $staticPGAssets->{$file};

		   # If the file was not found in the lists, then just use the given file and assume its path is relative to the
		   # render app public folder.
			return $c->url_for('publicFile', static => $file)->to_string;
		}
	);
	return;
}

sub readJSON ($filePath) {
	return unless -r $filePath;
	my $data = decode_json($filePath->slurp('UTF-8'));
	die "FATAL: Unable to open '$filePath'!" if $@;
	return $data;
}

sub getThirdPartyAssetURL ($c, $file, $dependencies, $routeName) {
	for (keys %$dependencies) {
		if ($file =~ /^node_modules\/$_\/(.*)$/) {
			if ($c->config->{thirdPartyAssetsUseCDN}) {
				return
					"https://cdn.jsdelivr.net/npm/$_\@"
					. substr($dependencies->{$_}, 1) . '/'
					. ($1 =~ s/(?:\.min)?\.(js|css)$/.min.$1/gr);
			} else {
				return $c->url_for($routeName, static => $file)->query(version => $dependencies->{$_} =~ s/#/@/gr)
					->to_string;
			}
		}
	}
	return;
}

1;
